inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-standard:
    - config/default.yml
    - config/minitest.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - "ext/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "test/progit/**/*"
